spring:
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: lb://serviceA
          predicates:
            - Path=/serviceA/**
          filters:
            - StripPrefix=1
        - id: serviceB
          uri: lb://serviceB
          predicates:
            - Path=/serviceB/**
          filters:
            - StripPrefix=1

server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
